baseURL = "https://iliathoughts.com"
languageCode = "en-us"
title = "Ilia thoughts"
theme = "monopriv"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[server]
  [[server.headers]]
    [server.headers.values]
      Cross-Origin-Opener-Policy = "same-origin"
      Cross-Origin-Embedder-Policy = "require-corp"

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".json$", ".wasm$",".data$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "mysite"
URL = "s3://iliathoughts.com?region=ap-southeast-2"

[[deployment.matchers]]
#  Cache static assets for 1 hour.
pattern = "^.+\\.(html|js|wasm|css|svg|ttf|yaml)$"
cacheControl = "must-revalidate, no-cache, max-age=0, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(data)$"
cacheControl = "max-age=3600, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|obj)$"
cacheControl = "max-age=3600, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(xml|json)$"
cacheControl = "max-age=3600, no-transform, public"
gzip = false

[params]
about = "Thoughts on data analytics, software development, and other things."
img = "img/logo.png"
github = "https://github.com/bezdomniy"
email = "ilia.shibaev@protonmail.com"
# site meta description
metadesc = "A simple privacy oriented bootstrap hugo blog"
# site meta keywords
metakeys = "hugo, simple, minimal, bootstrap, blog"
# enable/disable disqus comments 
disqus = false 
# enable/disable google analytics 
analytics = false 